version: "3.4"
services:
  mayday:
    image: ${DTR_ADDRESS_WITH_ACCOUNT}/mayday:${VERSION}-server
    build: 
      context: .
      target: server
    tty: true
    ports:
      - "8050:8050"
    networks:
      - backend
  client:
    image: ${DTR_ADDRESS_WITH_ACCOUNT}/mayday:${VERSION}-client
    build: 
      context: .
      target: client
    tty: true
    networks:
      - backend

networks:
  backend:
    driver: "bridge"